package br.com.chikasawa.persistencia;

import java.sql.Connection;
import java.sql.Statement;

import br.com.chikasawa.DAO.Pessoa;
import br.com.chikasawa.file.LeituraDeArquivo;
import br.com.chikasawa.file.*;

public  class ControladorDePersistencia {
	
	static String [] queries = {
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')",
		    "insert into pessoa (nome) values ('Chika')",
		    "insert into pessoa (nome) values ('Ricardo')",
		    "insert into pessoa (nome) values ('Fabio')"
		    
		};
	
	
	
	public  void salvarRegistro() throws Exception
    {  
		Conexao conexao = new Conexao();
        conexao.conecta();
        System.out.println("conexao efetuada");
        Connection con = conexao.getConection();       
        Statement st = con.createStatement();
       

        //String queries = "INSERT INTO pessoa(nome) values ('" + p.getNome() + "')";
        for (String query : queries) {
            st.addBatch(query);
        }
       
        st.executeBatch();
        st.close();
        conexao.desconecta();
    }

}
